dist: xenial
language: rust
rust:
  - stable
  - beta
  - nightly
install:
  - git clone --recursive https://github.com/WebAssembly/wabt
  - pushd wabt && make && sudo make install && popd
script:
  - cargo build --verbose
  - cargo test --verbose -- --nocapture --test-threads 1
